import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { requireEnvsSet } from "../lib/env.ts";

const RETARGET_INTERVAL = 2016;
const MIN_CONFIRMATIONS = 6;
const OUTPUT_PATH = resolve(import.meta.dirname, "../contracts/HashpriceBTCDeploy.sol");

interface RpcResponse {
  error?: { message: string };
  result: unknown;
}

async function bitcoinRpc(rpcUrl: string, method: string, params: unknown[] = []) {
  const url = new URL(rpcUrl);
  const headers: Record<string, string> = { "Content-Type": "application/json" };

  if (url.username) {
    const credentials = Buffer.from(`${url.username}:${url.password}`).toString("base64");
    headers["Authorization"] = `Basic ${credentials}`;
    url.username = "";
    url.password = "";
  }

  const res = await fetch(url.toString(), {
    method: "POST",
    headers,
    body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }),
  });
  const json = (await res.json()) as RpcResponse;
  if (json.error) throw new Error(`Bitcoin RPC error: ${json.error.message}`);
  return json.result;
}

function reverseHex(hex: string): string {
  const clean = hex.replace(/^0x/, "");
  const bytes = clean.match(/.{2}/g);
  if (!bytes) throw new Error("Invalid hex string");
  return `0x${bytes.reverse().join("")}`;
}

async function main() {
  const env = <{ BITCOIN_RPC_URL: string }>requireEnvsSet("BITCOIN_RPC_URL");

  const info = (await bitcoinRpc(env.BITCOIN_RPC_URL, "getblockchaininfo")) as { blocks: number };
  const tipHeight = info.blocks;
  console.log("Node tip:", tipHeight);

  const height = process.env.CHECKPOINT_HEIGHT
    ? Number(process.env.CHECKPOINT_HEIGHT)
    : tipHeight - MIN_CONFIRMATIONS;

  if (height > tipHeight - MIN_CONFIRMATIONS) {
    throw new Error(
      `Height ${height} too close to tip ${tipHeight} (need >= ${MIN_CONFIRMATIONS} confirmations)`,
    );
  }

  console.log("Checkpoint height:", height);

  type BlockHeader = {
    height: number;
    time: number;
    bits: string;
    hash: string;
    confirmations: number;
  };

  async function fetchHeader(h: number): Promise<BlockHeader> {
    const hash = (await bitcoinRpc(env.BITCOIN_RPC_URL, "getblockhash", [h])) as string;
    return (await bitcoinRpc(env.BITCOIN_RPC_URL, "getblockheader", [hash, true])) as BlockHeader;
  }

  const header = await fetchHeader(height);

  const blockHashLE = reverseHex(header.hash);
  const timestamp = header.time;
  const isoDate = new Date(timestamp * 1000).toISOString();

  console.log("Block hash:", header.hash);
  console.log("Block hash (LE):", blockHashLE);
  console.log("Timestamp:", timestamp, `(${isoDate})`);
  console.log("nBits:", `0x${header.bits}`);
  console.log("Confirmations:", header.confirmations);

  const epochStartHeight = height - (height % RETARGET_INTERVAL);
  let epochStartTimestamp: number;
  let epochStartBits: string;

  if (epochStartHeight === height) {
    epochStartTimestamp = timestamp;
    epochStartBits = header.bits;
    console.log("Checkpoint is at epoch boundary.");
  } else {
    console.log(`Fetching epoch start block ${epochStartHeight}...`);
    const epochHeader = await fetchHeader(epochStartHeight);
    epochStartTimestamp = epochHeader.time;
    epochStartBits = epochHeader.bits;
    console.log(
      "Epoch start timestamp:",
      epochStartTimestamp,
      `(${new Date(epochStartTimestamp * 1000).toISOString()})`,
    );
    console.log("Epoch start nBits:", `0x${epochStartBits}`);
  }
  console.log();

  const sol = `// SPDX-License-Identifier: MIT
// AUTO-GENERATED by generate-checkpoint.ts — do not edit manually.
pragma solidity >=0.8.0;

import {HashpriceBTC} from "./HashpriceBTC.sol";

/// @title HashpriceBTCDeploy
/// @notice HashpriceBTC anchored at block ${height} (${isoDate}), epoch start ${epochStartHeight}
contract HashpriceBTCDeploy is HashpriceBTC {
    constructor()
        HashpriceBTC(
            ${blockHashLE}, // block ${height}
            ${height}, // height
            ${timestamp}, // ${isoDate}
            0x${header.bits}, // nBits
            ${epochStartTimestamp}, // epoch start (block ${epochStartHeight})
            0x${epochStartBits} // epoch start nBits
        )
    {}
}
`;

  writeFileSync(OUTPUT_PATH, sol);
  console.log("Generated:", OUTPUT_PATH);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
