// SPDX-License-Identifier: MIT
// AUTO-GENERATED by generate-checkpoint.ts — do not edit manually.
pragma solidity >=0.8.0;

import {HashpriceBTC} from "./HashpriceBTC.sol";

/// @title HashpriceBTCDeploy
/// @notice HashpriceBTC anchored at block 959857 (2026-07-27T16:25:25.000Z), epoch start 959616
contract HashpriceBTCDeploy is HashpriceBTC {
    constructor()
        HashpriceBTC(
            0x5875a93c348f1d4140fb54521adbf453b1937ec0978901000000000000000000, // block 959857
            959857, // height
            1785169525, // 2026-07-27T16:25:25.000Z
            0x17023ad4, // nBits
            1785019866, // epoch start (block 959616)
            0x17023ad4 // epoch start nBits
        )
    {}
}
