// SPDX-License-Identifier: MIT
// AUTO-GENERATED by generate-checkpoint.ts — do not edit manually.
// Regenerate:
//   BITCOIN_RPC_URL=... CHECKPOINT_HEIGHT=944486 npx hardhat run scripts/generate-checkpoint.ts
pragma solidity >=0.8.0;

import {HashpriceBTC} from "./HashpriceBTC.sol";

/// @title HashpriceBTCDeploy
/// @notice HashpriceBTC anchored at block 944486 (2026-04-10T15:49:18.000Z), epoch start 943488
contract HashpriceBTCDeploy is HashpriceBTC {
    constructor()
        HashpriceBTC(
            0x77487db230ce2c70035e2a52a315ab4e9275abcfbe5901000000000000000000, // block 944486
            944486, // height
            1775836158, // 2026-04-10T15:49:18.000Z
            0x17020684, // nBits
            1775208520, // epoch start (block 943488)
            0x17020684 // epoch start nBits
        )
    {}
}
