export const hashpriceBTCAbi = [
  {
    inputs: [],
    name: "chainTipBE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "state",
    outputs: [
      { internalType: "uint32", name: "chainHeight", type: "uint32" },
      { internalType: "uint32", name: "blockCount", type: "uint32" },
      { internalType: "uint32", name: "epochStartTimestamp", type: "uint32" },
      { internalType: "uint32", name: "epochStartNBits", type: "uint32" },
      { internalType: "uint32", name: "lastSubmittedAt", type: "uint32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "confirmedHeight",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes", name: "header", type: "bytes" },
      { internalType: "bytes", name: "coinbaseTx", type: "bytes" },
      { internalType: "bytes32[]", name: "merkleProof", type: "bytes32[]" },
    ],
    name: "submitBlock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint32", name: "ancestorHeight", type: "uint32" },
      { internalType: "bytes", name: "headers", type: "bytes" },
      { internalType: "bytes[]", name: "coinbaseTxs", type: "bytes[]" },
      { internalType: "bytes32[][]", name: "merkleProofs", type: "bytes32[][]" },
    ],
    name: "submitBlocks",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "latestRoundData",
    outputs: [
      { internalType: "uint80", name: "roundId", type: "uint80" },
      { internalType: "int256", name: "answer", type: "int256" },
      { internalType: "uint256", name: "startedAt", type: "uint256" },
      { internalType: "uint256", name: "updatedAt", type: "uint256" },
      { internalType: "uint80", name: "answeredInRound", type: "uint80" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "blockHash", type: "bytes32" },
      { indexed: true, internalType: "uint32", name: "height", type: "uint32" },
      { indexed: false, internalType: "uint64", name: "fees", type: "uint64" },
    ],
    name: "BlockSubmitted",
    type: "event",
  },
] as const;
