# Price feed entities

type HashpriceMeta @entity(immutable: true) {
  id: Int8!
  hashpriceUsdAddress: Bytes!
  hashpriceBtcAddress: Bytes!
  btcUsdAddress: Bytes!
  hashpriceUsdDecimals: Int8!
  hashpriceBtcDecimals: Int8!
  btcUsdDecimals: Int8!
  startBlock: BigInt!
  pollingBlockInterval: BigInt!
}

type HashpriceUsd @entity(timeseries: true) {
  id: Int8!
  price: BigInt!
  timestamp: Timestamp!
  blockNumber: BigInt!
}

type HashpriceBtc @entity(timeseries: true) {
  id: Int8!
  price: BigInt!
  timestamp: Timestamp!
  blockNumber: BigInt!
}

type BtcUsd @entity(timeseries: true) {
  id: Int8!
  price: BigInt!
  timestamp: Timestamp!
  blockNumber: BigInt!
}

# Candle aggregations

type HashpriceUsdCandle @aggregation(intervals: ["hour", "day"], source: "HashpriceUsd") {
  id: Int8!

  high: BigInt! @aggregate(fn: "max", arg: "price")
  low: BigInt! @aggregate(fn: "min", arg: "price")
  sum: BigInt! @aggregate(fn: "sum", arg: "price")
  count: BigInt! @aggregate(fn: "count", arg: "price")

  timestamp: Timestamp!
}

# Hashprice/BTC

type HashpriceBtcCandle @aggregation(intervals: ["hour", "day"], source: "HashpriceBtc") {
  id: Int8!

  high: BigInt! @aggregate(fn: "max", arg: "price")
  low: BigInt! @aggregate(fn: "min", arg: "price")
  sum: BigInt! @aggregate(fn: "sum", arg: "price")
  count: BigInt! @aggregate(fn: "count", arg: "price")

  timestamp: Timestamp!
}

# BTC/USD

type BtcUsdCandle @aggregation(intervals: ["hour", "day"], source: "BtcUsd") {
  id: Int8!

  high: BigInt! @aggregate(fn: "max", arg: "price")
  low: BigInt! @aggregate(fn: "min", arg: "price")
  sum: BigInt! @aggregate(fn: "sum", arg: "price")
  count: BigInt! @aggregate(fn: "count", arg: "price")

  timestamp: Timestamp!
}
